export interface destinatarios{
    id_usuario:number | any, 
    id_cat_destinatario:number | any, 
    id_gestion_oficios :number | any, 
    id_direccion:number | any, 
    text_direccion:string | any,
    id_area:number | any, 
    area_texto:string | any,
    numero_empledo:string | any,
    text_nombre_empleado:string | any,
    foto:string | any,
    id_oficio:number | any, 
    estatus:number | any, 
    id_estatusregistro_destinatario:number | any, 
    respuesta:string | any,
    id_asignacion:string | any,
    sello_digital:string | any,
    con_copia:string | any,
    activo:string | any,
}