export interface destinatarioConOficio{
    id_usuario:number | any, 
    id_cat_destinatario:number | any, 
    id_gestion_oficios :number | any, 
    id_direccion:number | any, 
    text_direccion:string | any,
    id_area:number | any, 
    area_texto:string | any,
    numero_empledo:string | any,
    text_nombre_empleado:string | any,
    foto:string | any,
    id_oficio:number | any, 
    estatus:number | any, 
    id_estatusregistro_destinatario:number | any, 
    respuesta:string | any,
    id_asignacion:string | any,
    sello_digital:string | any,
    con_copia:string | any,
    id_oficios:number | any,  
    oficio:number | any,  
    text_oficio:string | any,
    tipo_oficio : string |any,
    text_tipo : string |any,
    folio : string |any,
    numero_oficio : string |any,
    fecha_hora : string |any,
    caso_cop : string |any,
    asunto : string |any,
    contenido : string |any,
    archivo_oficio : string |any,
    otro : string |any,
    id_estatusgestion_oficios:number | any,  
    activo:number | any,  



}