export interface historialMastercatalogo_empleadosTable{
  id_historialMastercatalogo_empleados :number | any,  
  id_cat_empleados : string|any,  
  id_usuario : string|any,  
  nombre_completo : string|any,  
  numero_empleado : string|any,  
  cargo : string|any,  
  direccion : string|any,  
  direccion_texto : string|any,  
  subdireccion : string|any,  
  area : string|any,  
  area_texto : string|any,  
  nombreJefe : string|any,  
  cargoJefe : string|any,  
  correo_institucional : string|any,  
  telefono_opdm : string|any,  
  url : string|any,  
  codigo_qr : string|any,  
  foto : string|any,  
}
