export interface Nuevotecnico{
  id_asignacion : number|any,
  finalizado   : number|any,
  id_gestion_oficio : number|any,  
  id_oficio : number|any,  
  numero_oficio : string|any,  
  id_direcion_firmante : number|any,  
  text_direccion_firmante : string|any,  
  id_area_firmante : number|any,  
  text_area_firmante : string|any,  
  numero_empleado_firmante : string|any,  
  id_direccion_asignacion : number|any,  
  text_direccion_asignacion : string|any,  
  id_area_asignacion : number|any,  
  text_area_asignacion : string|any,  
  numero_empleado_asignacion : string|any,  
  fecha_asignacion : string|any,  
  estatus_seguimiento : string|any,  
  observaciones : string|any,  
  porcentaje_seguimiento : number,  
  fecha_contestacion : string|any,  
  evidencia : string|any,  
  documento_oficio : string|any,  
  id_estatusseguimiento_tecnico : number|any,  
  activo     : number|any,  
  id_usuario : number|any,  
  numero_empleado_tecnico: number|any,  
  createdAt? : string|any,  
  nombre_tecnico : string|any,  
  foto_tecnico: string|any,  

  
}
