export interface cat_destinatarioTable {
  id_registro_destinatario: number | any,
  PaginaActual: string | any,
  finalizado: number | any,
  id_cat_destinatario: number | any,
  id_direccion: string | any,
  text_direccion: string | any,
  id_area: string | any,
  area_texto: string | any,
  numero_empledo: string | any,
  text_nombre_empleado: string | any,
  foto: string | any,
  id_oficio: string | any,
  estatus: number | any,
  id_estatusregistro_destinatario: number | any,
  activo: number | any,
  id_usuario: number | any,
  visto?: number | any,
  respuesta?: number | any,
  id_gestion_oficios?: number | any;
  con_copia: string | any,
  fecha_terminacion?: string | any,
  numero_oficio?: string | any,
  asunto?: string | any,

}
