export interface oficiosTable {
  id_asignacion?: number | any,
  id_tecnico?: number | any,
  id_gestion_oficios: number | any,
  PaginaActual: string | any,
  finalizado: number | any,
  id_oficios: number | any,
  oficio: string | any,
  text_oficio: string | any,
  tipo_oficio: string | any,
  text_tipo: string | any,
  numero_oficio: string | any,
  fecha_hora: string | any,
  caso_cop: string | any,
  asunto: string | any,
  contenido: string | any,
  archivo_oficio: string | any,
  otro: string | any,
  id_estatusgestion_oficios: number | any,
  activo: number | any,
  id_usuario: number | any,
  estatus_oficio?:number | any,
  createdAt?: string | any,
}
