export interface cat_firmanteTable{
  id_registro_quien_firma : number|any,
  PaginaActual : string|any,
  finalizado   : number|any,
  id_cat_firmante : number|any,  
  id_direccion : string|any,  
  text_direccion : string|any,  
  id_area : string|any,  
  area_texto : string|any,  
  numero_empledo : string|any,  
  text_nombre_empleado : string|any,  
  foto : string|any,  
  id_oficio : string|any,  
  otro : string|any,  
  id_estatusregistro_quien_firma : number|any,  
  activo     : number|any,  
  id_usuario : number|any,  
  id_gestion_oficios: number|any,  
}
